<a href="https://colab.research.google.com/github/anaswaraku/AdvancedPythonProgramming/blob/main/Advanced_NumPy_Concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Advanced NumPy Concepts

In [ ]:

import numpy as np


matrix = np.array([[1, 2], [3, 4]])

inverse_matrix = np.linalg.inv(matrix)
print("Original Matrix:")
print(matrix)
print("\nInverse Matrix:")
print(inverse_matrix)


Original Matrix:
[[1 2]
 [3 4]]

Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


Matrix, Eigenvalues and Eigenvectors
Write a Python program to create a matrix and apply all matrix operations

In [ ]:
import numpy as np

# Create a matrix
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Print the matrix
print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Matrix operations

# Addition
print("Addition:\n", A + B)

# Subtraction
print("Subtraction:\n", A - B)

# Multiplication
print("Multiplication:\n", A @ B)

# Transpose
print("Transpose:\n", A.T)

# Determinant
print("Determinant:\n", np.linalg.det(A))

# Inverse
print("Inverse:\n", np.linalg.inv(A))

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Determinant:
 -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Solving Linear Equations
Write a Python program to solve a system of linear equations using NumPy. Solve the system:
2x + 3y = 5
4x + y = 6

In [ ]:
import numpy as np

# Define the coefficients matrix A and the constants vector b
A = np.array([[2, 3], [4, 1]])
b = np.array([5, 6])

# Solve the system of equations using NumPy's solve function
x = np.linalg.solve(A, b)

# Print the solution
print(x)

[1.3 0.8]


Random Sampling
Write a Python program to generate a 5x5 matrix of random numbers from a normal distribution using NumPy.

In [7]:
import numpy as np

matrix = np.random.normal(size=(5, 5))

print(matrix)


[[-1.70135835 -0.126137   -0.99755167  0.55633669 -0.13175698]
 [ 0.33948482  0.96817551  0.15721856 -1.07569504  0.12432962]
 [ 0.27750946 -0.83079599  0.22532562  0.54045809  0.45141828]
 [-1.07032429 -1.85327513  0.69158817 -0.26127296  1.65705103]
 [ 0.91333613 -0.34297368  0.26852973 -0.63265104  1.02843662]]


Statistical Functions
Write a Python program using NumPy to calculate the mean, median, and standard deviation of an array of numbers.

In [8]:
import numpy as np

# create a 1D array with 5 elements
array1 = np.array([1, 2, 3, 4, 5])

median = np.median(array1)
print(median)
mean = np.mean(array1)
print(mean)
std = np.std(array1)
print(std)

3.0
3.0
1.4142135623730951
