<a href="https://colab.research.google.com/github/anaswaraku/AdvancedPythonProgramming/blob/main/NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import random
a = np.array([random.randint(1, 10) for _ in range(3)])
b=np.array([random.randint(1, 10) for _ in range(3)])
c=np.array([random.randint(1, 10) for _ in range(3)])
arr=np.array([a,b,c])
print(arr)

[[4 3 7]
 [8 3 1]
 [1 5 1]]


Write a Python program using NumPy to create a 3x3 matrix with values ranging from 1 to 9.


In [11]:
import numpy as np

matrix = np.arange(1, 10).reshape(3, 3)

print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Write a Python program to create a NumPy array and reverse its elements.


In [15]:
arr = np.arange(1,10)
print("Original array:", arr)
reversed_arr = np.flip(arr)#arr[::-1]
print("Reversed array:", reversed_arr)

Original array: [1 2 3 4 5 6 7 8 9]
Reversed array: [9 8 7 6 5 4 3 2 1]


Write a Python program to extract a 2x2 submatrix from a 3x3 matrix using NumPy slicing.


In [20]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slicing a subarray
# Get a 2x2 subarray
sub_matrix = matrix[0:2, 1:3]
#0:2 selects rows 0 and 1.
#1:3 selects columns 1 and 2.
print(sub_matrix)

[[2 3]
 [5 6]]


Write a Python program to perform matrix multiplication using NumPy's dot() function.

In [21]:

# importing the module
import numpy as np

# creating two matrices
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
print("Matrix p :")
print(p)
print("Matrix q :")
print(q)

# computing product
result = np.dot(p, q)

# printing the result
print("The matrix multiplication is :")
print(result)

Matrix p :
[[1, 2], [2, 3]]
Matrix q :
[[4, 5], [6, 7]]
The matrix multiplication is :
[[16 19]
 [26 31]]
